# Copyright 2019-2022 DADoES, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root directory in the "LICENSE" file or at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#The package.yml file contains the location of models to be loaded from Blender files.
#The name of the objects map to the name of a collection in the blender file.

# This package uses bundled package data. The data is located in the package itself under
# a sub directory defined by the 'example' logical name.
# The logical name is then used in the "objects" block to refer to that location.
# For instance, "example:LowPoly.blend" refers to "data/LowPoly.blend" in the example
# package directory
volumes:
  factory_temp: 'ee6968eb-5391-436c-8662-3818f559bf64'

# Define objects.
objects:

  Warehouse:
    filename: factory_temp:Warehouse.blend
  
  Box1:
    filename: factory_temp:Box1.blend