version: 2
nodes:
  
  Box1:
    nodeClass: Box1

  ObjectPlacement:
    nodeClass: Random Placement
    values: {Number of Objects: 7}
    links:
      Object Generators:
      - {sourceNode: Box1, outputPort: Box1 Generator}
      Warehouse Generator: 
        - {sourceNode: Warehouse, outputPort: Warehouse Generator}

  Warehouse:
    nodeClass: Warehouse

  Render:
    nodeClass: Render
    values:
      Width (px): 1024
      Height (px): 1024
    links:
      Objects:
      - {sourceNode: ObjectPlacement, outputPort: Objects}
    
